<%@ page language="java"
    contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>

<%@ page import="java.util.Map" %>
<%@ page import="com.sunrise.model.User" %>

<%
    User loggedUser =
        (User) session.getAttribute("loggedUser");

    if (loggedUser == null) {
        response.sendRedirect("login.jsp");
        return;
    }

    Map<String, Integer> appointmentsByDentist =
        (Map<String, Integer>) request.getAttribute("appointmentsByDentist");

    Map<String, Integer> appointmentsByTreatment =
        (Map<String, Integer>) request.getAttribute("appointmentsByTreatment");

    Integer totalBills =
        (Integer) request.getAttribute("totalBills");

    Double totalRevenue =
        (Double) request.getAttribute("totalRevenue");

    Double averageBillAmount =
        (Double) request.getAttribute("averageBillAmount");

    if (totalBills == null) {
        totalBills = 0;
    }

    if (totalRevenue == null) {
        totalRevenue = 0.0;
    }

    if (averageBillAmount == null) {
        averageBillAmount = 0.0;
    }
%>

<!DOCTYPE html>
<html>

<head>

    <meta charset="UTF-8">

    <title>Reports - Sunrise Dental Clinic</title>

    <link rel="stylesheet"
          href="<%= request.getContextPath() %>/css/style.css">

</head>

<body>

<div class="page-container">

    <div class="page-header">

        <h1>Sunrise Dental Clinic Reports</h1>

        <p>
            Generated by
            <strong><%= loggedUser.getFullName() %></strong>
        </p>

    </div>


    <div class="stats-grid">

        <div class="stat-card">

            <h3>Total Bills</h3>

            <div class="stat-value">
                <%= totalBills %>
            </div>

        </div>


        <div class="stat-card">

            <h3>Total Revenue</h3>

            <div class="stat-value">

                LKR
                <%= String.format(
                        "%.2f",
                        totalRevenue
                    ) %>

            </div>

        </div>


        <div class="stat-card">

            <h3>Average Bill Amount</h3>

            <div class="stat-value">

                LKR
                <%= String.format(
                        "%.2f",
                        averageBillAmount
                    ) %>

            </div>

        </div>

    </div>


    <div class="card">

        <div class="page-header">

            <h2>Appointments by Dentist</h2>

            <p>
                Number of appointments assigned to each dentist.
            </p>

        </div>


        <div class="table-wrapper">

            <table>

                <thead>

                    <tr>
                        <th>Dentist</th>
                        <th>Total Appointments</th>
                    </tr>

                </thead>


                <tbody>

                <%
                    if (
                        appointmentsByDentist != null &&
                        !appointmentsByDentist.isEmpty()
                    ) {

                        for (
                            Map.Entry<String, Integer> entry :
                            appointmentsByDentist.entrySet()
                        ) {
                %>

                    <tr>

                        <td>
                            <%= entry.getKey() %>
                        </td>

                        <td>
                            <%= entry.getValue() %>
                        </td>

                    </tr>

                <%
                        }

                    } else {
                %>

                    <tr>

                        <td colspan="2"
                            class="text-center">

                            No appointment data available.

                        </td>

                    </tr>

                <%
                    }
                %>

                </tbody>

            </table>

        </div>

    </div>


    <div class="card">

        <div class="page-header">

            <h2>Appointments by Treatment</h2>

            <p>
                Number of appointments recorded for each treatment type.
            </p>

        </div>


        <div class="table-wrapper">

            <table>

                <thead>

                    <tr>
                        <th>Treatment</th>
                        <th>Total Appointments</th>
                    </tr>

                </thead>


                <tbody>

                <%
                    if (
                        appointmentsByTreatment != null &&
                        !appointmentsByTreatment.isEmpty()
                    ) {

                        for (
                            Map.Entry<String, Integer> entry :
                            appointmentsByTreatment.entrySet()
                        ) {
                %>

                    <tr>

                        <td>
                            <%= entry.getKey() %>
                        </td>

                        <td>
                            <%= entry.getValue() %>
                        </td>

                    </tr>

                <%
                        }

                    } else {
                %>

                    <tr>

                        <td colspan="2"
                            class="text-center">

                            No treatment data available.

                        </td>

                    </tr>

                <%
                    }
                %>

                </tbody>

            </table>

        </div>

    </div>


    <div class="action-buttons no-print">

        <button type="button"
                class="btn btn-primary"
                onclick="window.print()">

            Print Report

        </button>


        <a href="dashboard"
           class="btn btn-secondary">

            Back to Dashboard

        </a>

    </div>

</div>

</body>

</html>